In [11]:
import torch
import numpy as np

In [2]:
x = torch.arange(4).view(2, 2)
x

tensor([[0, 1],
        [2, 3]])

In [3]:
x.shape

torch.Size([2, 2])

In [4]:
x.rot90(1, [0,1])

tensor([[1, 3],
        [0, 2]])

In [5]:
x.rot90(2, [0,1])

tensor([[3, 2],
        [1, 0]])

In [3]:
x = torch.arange(8).view(2, 2, 2)
x

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])

In [4]:
torch.rot90(x, 1, [1, 2])

tensor([[[1, 3],
         [0, 2]],

        [[5, 7],
         [4, 6]]])

In [5]:
torch.empty(0)

tensor([])

In [8]:
z = torch.zeros(4)
z

tensor([0., 0., 0., 0.])

In [9]:
torch.nonzero(z == 0)

tensor([[0],
        [1],
        [2],
        [3]])

In [13]:
x2 = torch.from_numpy(np.array([0,1,1,0,1]))

In [14]:
torch.nonzero(x2 == 0)

tensor([[0],
        [3]])

In [15]:
torch.argmax(x)

tensor(7)

In [16]:
x

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])

In [19]:
x.data

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])